### Recuperar todos los libros
GET http://localhost:3001/api/books


### Recuperar un libro
GET http://localhost:3001/api/books/66043e56127e03d5146ff72b


### Crear un nuevo libro
POST http://localhost:3001/api/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impob25kb2VAZXhhbXBsZS5jb20iLCJpZCI6IjY2MDQ1MTZiNDcxOThhOTI0NDQzYTEyNCIsImlhdCI6MTcxMTkyMDA1MX0.Jmz0UaSkpN14-7k2XY2KsabUenF50GyZgKPvJ3U8euk

{
  "title": "La psicología del dinero",
  "author": "Morgan Housel",
  "userComment": "Genial libro",
  "rating": 5
}

### Eliminar un libro
DELETE http://localhost:3001/api/books/66043e56127e03d5146ff72b


### Actualizar un libro
PUT http://localhost:3001/api/books/6604453baf69e57bfdc8a469
Content-Type: application/json

{
  "rating": 9
}