### Recuperar todos los libros
GET http://localhost:3001/api/books


### Recuperar un libro
GET http://localhost:3001/api/books/66043e56127e03d5146ff72b


### Crear un nuevo libro
POST http://localhost:3001/api/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impob25kb2VAZXhhbXBsZS5jb20iLCJpZCI6IjY2MDQ1MTZiNDcxOThhOTI0NDQzYTEyNCIsImlhdCI6MTcxMTkyMDA1MX0.Jmz0UaSkpN14-7k2XY2KsabUenF50GyZgKPvJ3U8euk

{
  "title": "La psicología del dinero",
  "author": "Morgan Housel",
  "userComment": "Genial libro",
  "rating": 5
}

### Eliminar un libro
DELETE http://localhost:3001/api/books/660d6bed9dc223b8a808fcde
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZlbGlwZWFuZHJlc2xvcGV6OTFAZ21haWwuY29tIiwiaWQiOiI2NjBjOGE5YTE4YzM5MjViMGZhNDZlMmIiLCJpYXQiOjE3MTIxNzc3MDUsImV4cCI6MTcxMjc4MjUwNX0.io5zxxryEXBicLE1BLWEyMeoBRDgcKO1In9a5YcgJxM


### Actualizar un libro
PUT http://localhost:3001/api/books/660d67399dc223b8a808fca4
Content-Type: application/json

{
  "rating": 9
}